title: Aluminum Overcast
description: Keep Looking Up # this means to ignore newlines until "baseurl:"
email: clintfandango@pm.me
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://aluminumovercast.com" # the base hostname & protocol for your site
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-minima

# Add any other configuration variables here
