name: Aluminum Overcast
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
