title: Aluminum Overcast
description: Keep Looking Up # this means to ignore newlines until "baseurl:"
email: clintfandango@pm.me
markdown: kramdown
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Add any other configuration variables here
