title: Aluminum Overcast
description: Keep Looking Up # this means to ignore newlines until "baseurl:"
email: clintfandango@pm.me
baseurl: "/clintfandango.github.io"  # the subpath of your site, e.g. /blog
url: "https://aluminumovercast.com"  # the base hostname & protocol for your site
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-tagging
# Add any other configuration variables here
tag_page_dir: tag
tag_page_layout: tag
