title: Aluminum Overcast
description: Putting Things Together # this means to ignore newlines until "baseurl:"
email: clintfandango@pm.me
mastodon: clintfandango@mastodon.social
baseurl: ""  # the subpath of your site, e.g. /blog
include: ["/.well-known" ]
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-tagging
# Add any other configuration variables here
tag_page_dir: tag
tag_page_layout: tag
